apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pinger
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: radial/busyboxplus:curl
            command: ["curl", "dan-hypothesizer"]
          restartPolicy: OnFailure
