apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-spoonerisms
  labels:
    app: spoonerisms
    varowner: varowner
spec:
  selector:
    matchLabels:
      app: spoonerisms
      varowner: varowner
  template:
    metadata:
      labels:
        app: spoonerisms
        tier: web
        varowner: varowner
    spec:
      containers:
      - name: spoonerisms
        image: gcr.io/windmill-public-containers/servantes/spoonerisms
        command: ["node", "/app/index.js"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
