apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spoonerisms
  labels:
    app: spoonerisms
spec:
  template:
    metadata:
      labels:
        app: spoonerisms
        tier: web
    spec:
      containers:
      - name: spoonerisms
        image: gcr.io/windmill-public-containers/servantes/spoonerisms
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: spoonerisms
  labels:
    app: spoonerisms
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: spoonerisms
