apiVersion: apps/v1
kind: Deployment
metadata:
  name: varowner-vigoda
  labels:
    app: vigoda
    varowner: varowner
spec:
  selector:
    matchLabels:
      app: vigoda
      varowner: varowner
  template:
    metadata:
      labels:
        app: vigoda
        tier: web
        varowner: varowner
    spec:
      containers:
      - name: vigoda
        image: gcr.io/windmill-public-containers/servantes/vigoda
        command: ["/go/bin/vigoda"]
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/vigoda/web/templates"
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "10m"
